name: Push da imagem docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Código
        uses: actions/checkout@v2

      - name: Configurar Buildx
        uses: docker/setup-buildx-action@v1

      - name: Logar DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build e push da imagem
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sauter-university:latest
          tags: ${{ secrets.DOCKERHUB_PASSWORD}}/sauter-university:latest
